# Generated by Django 5.1.5 on 2025-04-13 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_null_from_last_level_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='external_author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор (оригинал)'),
        ),
        migrations.AddField(
            model_name='article',
            name='original_url',
            field=models.URLField(blank=True, null=True, verbose_name='Оригинальная ссылка'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='action_type',
            field=models.CharField(choices=[('article_create', 'Создание статьи'), ('article_edit', 'Редактирование статьи'), ('article_delete', 'Удаление статьи'), ('comment_add', 'Добавление комментария'), ('profile_update', 'Обновление профиля'), ('digest_update', 'Обновление дайджеста')], max_length=50, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время действия'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['level'], name='Articles_level_bd61c1_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured'], name='Articles_is_feat_b04eba_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['publication_date'], name='Articles_publica_c49d74_idx'),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['user', 'timestamp'], name='news_userac_user_id_5031dc_idx'),
        ),
    ]
